# Generated by Django 5.2.8 on 2025-11-17 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(default='Flight Booking', max_length=50)),
                ('required_trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], default='one_way', max_length=20)),
                ('required_origin', models.CharField(blank=True, max_length=100)),
                ('required_destination', models.CharField(blank=True, max_length=100)),
                ('required_departure_date', models.DateField(blank=True, null=True)),
                ('required_return_date', models.DateField(blank=True, null=True)),
                ('required_travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('required_passengers', models.PositiveIntegerField(default=1)),
                ('required_children', models.PositiveIntegerField(default=0)),
                ('required_infants', models.PositiveIntegerField(default=0)),
                ('require_passenger_details', models.BooleanField(default=True)),
                ('required_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instructions', models.TextField()),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('due_date', models.DateTimeField()),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('addon_grading_enabled', models.BooleanField(default=True, help_text='Enable grading for add-ons')),
                ('required_addon_points', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum points required from add-ons', max_digits=6)),
                ('activity_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('is_code_active', models.BooleanField(default=False)),
                ('code_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='instructorapp.activity')),
            ],
            options={
                'ordering': ['-is_primary', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this add-on is mandatory for the activity')),
                ('quantity_per_passenger', models.PositiveIntegerField(default=1, help_text='How many of this add-on each passenger should have')),
                ('points_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Points awarded for including this add-on', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions for this add-on', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_addons', to='instructorapp.activity')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requirements', to='flightapp.addon')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_addons', to='instructorapp.activitypassenger')),
            ],
            options={
                'verbose_name_plural': 'Activity Add-ons',
                'unique_together': {('activity', 'addon', 'passenger')},
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission')], default='submitted', max_length=20)),
                ('required_trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('required_travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('required_passengers', models.PositiveIntegerField(default=1)),
                ('required_children', models.PositiveIntegerField(default=0)),
                ('required_infants', models.PositiveIntegerField(default=0)),
                ('require_passenger_details', models.BooleanField(default=True)),
                ('required_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Points earned from add-ons', max_digits=6)),
                ('max_addon_points', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum possible points from add-ons', max_digits=6)),
                ('addon_feedback', models.TextField(blank=True, help_text='Feedback specific to add-on selection')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='instructorapp.activity')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='flightapp.booking')),
                ('required_destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_destinations', to='flightapp.airport')),
                ('required_origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_origins', to='flightapp.airport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='flightapp.student')),
            ],
            options={
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PracticeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('practice_type', models.CharField(choices=[('free_practice', 'Free Practice'), ('guided_practice', 'Guided Practice')], default='free_practice', max_length=20)),
                ('scenario_description', models.TextField(blank=True, null=True)),
                ('practice_requirements', models.JSONField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_booking', to='flightapp.booking')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_bookings', to='flightapp.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('section_code', models.CharField(max_length=50, unique=True)),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='flightapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='instructorapp.section'),
        ),
        migrations.CreateModel(
            name='SectionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='instructorapp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='flightapp.student')),
            ],
            options={
                'unique_together': {('section', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentSelectedAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_selected', models.PositiveIntegerField(default=1)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='instructorapp.activityaddon')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='flightapp.addon')),
                ('booking_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='flightapp.bookingdetail')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='instructorapp.activitysubmission')),
            ],
            options={
                'unique_together': {('submission', 'activity_addon', 'addon')},
            },
        ),
    ]
