# Generated by Django 5.2.6 on 2025-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0006_activity_addon_grading_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='required_max_price',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='required_max_price',
        ),
        migrations.AlterField(
            model_name='activityaddon',
            name='points_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Points awarded for including this add-on', max_digits=6),
        ),
    ]
