# Generated by Django 5.2.8 on 2025-11-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
        ('instructorapp', '0002_activitysubmissionpassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='activity_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengerinfos', to='instructorapp.activitysubmission'),
        ),
        migrations.AddField(
            model_name='passengerinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
